[versions]
agp = "8.13.2"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
uiTextGoogleFonts = "1.10.0"
androidLotieCompose = "6.7.1"
navVersion = "2.9.6"
coil_version = "2.7.0"
ktor_version = "3.3.3"
serialization_version = "1.9.0"
serialization_plugin_version = "2.3.0"
koin_version = "4.1.1"
room_version = "2.8.4"
ksp_version = "2.0.21-1.0.27"
shimmer_version = "1.3.3"
accompanist_swipe_version = "0.36.0"
google_gms_play_services_auth = "21.5.0"
datastorePreferences = "1.2.0"
generativeai = "0.9.0"


[libraries]
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
android-lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "androidLotieCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navVersion" }
coil-kt = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil_version" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor_version" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor_version" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor_version" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor_version" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor_version" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization_version" }
ktor-client-logging-jvm = { group = "io.ktor", name = "ktor-client-logging-jvm", version.ref = "ktor_version" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor_version" }
koin-android-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin_version" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room_version" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room_version" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room_version" }
valentinilk-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "shimmer_version" }
google-accompanist-swiperefresher = { group ="com.google.accompanist", name ="accompanist-swiperefresh", version.ref = "accompanist_swipe_version"}
google-auth-service = {group="com.google.android.gms", name ="play-services-auth", version.ref= "google_gms_play_services_auth"}
androidx-datastore-preferences = {module = "androidx.datastore:datastore-preferences", version.ref="datastorePreferences"}
google-generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-serilization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization_plugin_version" }
google-ksp= { id = "com.google.devtools.ksp", version.ref = "ksp_version" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
[bundles]
ktor = [
    "ktor-client-core",
    "ktor-client-android",
    "ktor-client-okhttp",
    "ktor-client-serialization",
    "ktor-serialization-kotlinx-json",
    "kotlinx-serialization-json",
    "ktor-client-logging-jvm",
    "ktor-client-content-negotiation"
]

room = [
    "androidx-room-runtime",
    "androidx-room-ktx",
]
